# Generated by Django 5.0.7 on 2024-08-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='noImage.png', upload_to=''),
        ),
    ]
